name: AWS S3 workflow
on:
  push
env:
  BUCKET_NAME : "marketplace-portal-iam-access-bucket"
  AWS_REGION : "us-east-1"
  AWS_ACCOUNT_ID: "391091994985"
# permission can be added at job level or workflow level    
permissions:
      id-token: write
      contents: read
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-aws-s3-auth
          aws-region: ${{ env.AWS_REGION }}
       # Upload a template file to AWS s3
      - name:  copy marketplace-management-FSI-template.json to s3
        run: |
          aws s3 cp ../marketplace-management-FSI-template.json s3://${{ env.BUCKET_NAME }}/
