name: AWS S3 GitHub actions workflow
on:
  push
env:
  BUCKET_NAME : "storm-fsi-solutions"
  AWS_REGION : "us-east-1"
  AWS_ACCOUNT_ID: "391091994985"
  BUCKET_FOLDER_NAME: ${{ github.event.repository.name }}
  ROLE_NAME: "fsi-github-openid-role"
  TEMPLATE_FILE: "marketplace-management-FSI-template.json"
permissions:
      id-token: write
      contents: read
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Check if s3 bucket exists
        uses: actions/checkout@master
        id: check
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_S3_BUCKET: ${{ env.BUCKET_NAME }}
      - name: echo
        run: aws s3api head-bucket --bucket ${{ env.BUCKET_NAME }}
      - name: Create S3 bucket if doesn't exist
        run: aws s3 mb s3://${{ env.BUCKET_NAME }}
        env:
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
          ACL: "public"
      - name:  Copy template JSON file to s3
        run: aws s3 cp ${{ github.workspace }}/${{ env.TEMPLATE_FILE }} s3://${{ env.BUCKET_NAME }}/${{ env.BUCKET_FOLDER_NAME }}/
