name: AWS S3 GitHub actions workflow
on:
  push
env:
  BUCKET_NAME : "test-marketplace-strom-bucket"
  AWS_REGION : "eu-central-1"
  ROLE_NAME: "github-oidc-aws-connector"
  TEMPLATE_FILE: "marketplace-management-FSI-template.json"
permissions:
      id-token: write
      contents: read
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ env.ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Create bucket in S3
        run: aws s3api get-bucket-location --bucket ${{ env.BUCKET_NAME }} || aws s3api create-bucket --bucket ${{ env.BUCKET_NAME }} --region ${{ env.AWS_REGION }} --create-bucket-configuration LocationConstraint=${{ env.AWS_REGION }} --acl "public-read-write"
      - name: Grant public access
        run: aws s3api put-public-access-block --bucket ${{ env.BUCKET_NAME }} --public-access-block-configuration "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false"
      - name: Update policy.json
        run: echo "`jq '.Statement[0].Resource="arn:aws:s3:::${{ env.BUCKET_NAME }}/*"' ${{ github.workspace }}/policyBucket.json`" > ${{ github.workspace }}/policyBucket.json
      - name: read policy.json
        run: cat ${{ github.workspace }}/policyBucket.json
      - name: Add policy 
        run: aws s3api put-bucket-policy  --policy file://${{ github.workspace }}/policyBucket.json --bucket ${{ env.BUCKET_NAME }}
      - name: Enable acl public access
        run: aws s3api put-bucket-acl --bucket ${{ env.BUCKET_NAME }} --grant-full-control uri=http://acs.amazonaws.com/groups/global/AllUsers
      - name:  Copy template JSON file to s3
        run: aws s3 cp ${{ github.workspace }}/${{ env.TEMPLATE_FILE }} s3://${{ env.BUCKET_NAME }}/${{ github.event.repository.name }}/ --acl bucket-owner-full-control
