name: AWS S3 GitHub actions workflow
on:
  push
env:
  BUCKET_NAME : "storm-fsi-solutions-bucket"
  AWS_REGION : "eu-central-1"
  ROLE_NAME: "github-oidc-aws-connector"
  TEMPLATE_FILE: "marketplace-management-FSI-template.json"
permissions:
      id-token: write
      contents: read
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ env.ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Create S3 bucket
        run: aws s3api get-bucket-location --bucket ${{ env.BUCKET_NAME }} || aws s3 mb s3://${{ env.BUCKET_NAME }}
        env:
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
      - name:  Copy template JSON file to s3
        run: aws s3 cp ${{ github.workspace }}/${{ env.TEMPLATE_FILE }} s3://${{ env.BUCKET_NAME }}/${{ github.event.repository.name }}/
